// kotlin interop >>
//
//  Generated by :j2objc-kompat:j2objcKotlinTypes.  DO NOT EDIT!
//

#ifndef J2ObjC_kotlinTypes_h
#define J2ObjC_kotlinTypes_h

#if __has_include(<common/common.h>)
#import <common/common.h>
#else

#import <Foundation/NSArray.h>
#import <Foundation/NSDictionary.h>
#import <Foundation/NSError.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSSet.h>
#import <Foundation/NSString.h>
#import <Foundation/NSValue.h>

@class CommonArrayBridge, CommonKotlinArray<T>, CommonConcreteIterator<T>, CommonArrayListFactory, CommonByteArrayBridge, CommonKotlinByteArray, NSData, CommonHashMapBridge, CommonConcreteMutableEntry<K, V>, CommonHashSetFactory, CommonLinkedHashMapBridge, CommonLinkedHashSetFactory, CommonKotlinByteIterator;

@protocol CommonKotlinIterator, CommonKotlinMapEntry, CommonKotlinMutableMapMutableEntry, CommonKotlinMutableIterator, CommonKotlinListIterator, CommonKotlinMutableListIterator;

NS_ASSUME_NONNULL_BEGIN
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunknown-warning-option"
#pragma clang diagnostic ignored "-Wincompatible-property-type"
#pragma clang diagnostic ignored "-Wnullability"

#pragma push_macro("_Nullable_result")
#if !__has_feature(nullability_nullable_result)
#undef _Nullable_result
#define _Nullable_result _Nullable
#endif

__attribute__((swift_name("KotlinBase")))
@interface CommonBase : NSObject
- (instancetype)init __attribute__((unavailable));
+ (instancetype)new __attribute__((unavailable));
+ (void)initialize __attribute__((objc_requires_super));
@end

@interface CommonBase (CommonBaseCopying) <NSCopying>
@end

__attribute__((swift_name("KotlinMutableSet")))
@interface CommonMutableSet<ObjectType> : NSMutableSet<ObjectType>
@end

__attribute__((swift_name("KotlinMutableDictionary")))
@interface CommonMutableDictionary<KeyType, ObjectType> : NSMutableDictionary<KeyType, ObjectType>
@end

@interface NSError (NSErrorCommonKotlinException)
@property (readonly) id _Nullable kotlinException;
@end

__attribute__((swift_name("KotlinNumber")))
@interface CommonNumber : NSNumber
- (instancetype)initWithChar:(char)value __attribute__((unavailable));
- (instancetype)initWithUnsignedChar:(unsigned char)value __attribute__((unavailable));
- (instancetype)initWithShort:(short)value __attribute__((unavailable));
- (instancetype)initWithUnsignedShort:(unsigned short)value __attribute__((unavailable));
- (instancetype)initWithInt:(int)value __attribute__((unavailable));
- (instancetype)initWithUnsignedInt:(unsigned int)value __attribute__((unavailable));
- (instancetype)initWithLong:(long)value __attribute__((unavailable));
- (instancetype)initWithUnsignedLong:(unsigned long)value __attribute__((unavailable));
- (instancetype)initWithLongLong:(long long)value __attribute__((unavailable));
- (instancetype)initWithUnsignedLongLong:(unsigned long long)value __attribute__((unavailable));
- (instancetype)initWithFloat:(float)value __attribute__((unavailable));
- (instancetype)initWithDouble:(double)value __attribute__((unavailable));
- (instancetype)initWithBool:(BOOL)value __attribute__((unavailable));
- (instancetype)initWithInteger:(NSInteger)value __attribute__((unavailable));
- (instancetype)initWithUnsignedInteger:(NSUInteger)value __attribute__((unavailable));
+ (instancetype)numberWithChar:(char)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedChar:(unsigned char)value __attribute__((unavailable));
+ (instancetype)numberWithShort:(short)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedShort:(unsigned short)value __attribute__((unavailable));
+ (instancetype)numberWithInt:(int)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedInt:(unsigned int)value __attribute__((unavailable));
+ (instancetype)numberWithLong:(long)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedLong:(unsigned long)value __attribute__((unavailable));
+ (instancetype)numberWithLongLong:(long long)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedLongLong:(unsigned long long)value __attribute__((unavailable));
+ (instancetype)numberWithFloat:(float)value __attribute__((unavailable));
+ (instancetype)numberWithDouble:(double)value __attribute__((unavailable));
+ (instancetype)numberWithBool:(BOOL)value __attribute__((unavailable));
+ (instancetype)numberWithInteger:(NSInteger)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedInteger:(NSUInteger)value __attribute__((unavailable));
@end

__attribute__((swift_name("KotlinByte")))
@interface CommonByte : CommonNumber
- (instancetype)initWithChar:(char)value;
+ (instancetype)numberWithChar:(char)value;
@end

__attribute__((swift_name("KotlinUByte")))
@interface CommonUByte : CommonNumber
- (instancetype)initWithUnsignedChar:(unsigned char)value;
+ (instancetype)numberWithUnsignedChar:(unsigned char)value;
@end

__attribute__((swift_name("KotlinShort")))
@interface CommonShort : CommonNumber
- (instancetype)initWithShort:(short)value;
+ (instancetype)numberWithShort:(short)value;
@end

__attribute__((swift_name("KotlinUShort")))
@interface CommonUShort : CommonNumber
- (instancetype)initWithUnsignedShort:(unsigned short)value;
+ (instancetype)numberWithUnsignedShort:(unsigned short)value;
@end

__attribute__((swift_name("KotlinInt")))
@interface CommonInt : CommonNumber
- (instancetype)initWithInt:(int)value;
+ (instancetype)numberWithInt:(int)value;
@end

__attribute__((swift_name("KotlinUInt")))
@interface CommonUInt : CommonNumber
- (instancetype)initWithUnsignedInt:(unsigned int)value;
+ (instancetype)numberWithUnsignedInt:(unsigned int)value;
@end

__attribute__((swift_name("KotlinLong")))
@interface CommonLong : CommonNumber
- (instancetype)initWithLongLong:(long long)value;
+ (instancetype)numberWithLongLong:(long long)value;
@end

__attribute__((swift_name("KotlinULong")))
@interface CommonULong : CommonNumber
- (instancetype)initWithUnsignedLongLong:(unsigned long long)value;
+ (instancetype)numberWithUnsignedLongLong:(unsigned long long)value;
@end

__attribute__((swift_name("KotlinFloat")))
@interface CommonFloat : CommonNumber
- (instancetype)initWithFloat:(float)value;
+ (instancetype)numberWithFloat:(float)value;
@end

__attribute__((swift_name("KotlinDouble")))
@interface CommonDouble : CommonNumber
- (instancetype)initWithDouble:(double)value;
+ (instancetype)numberWithDouble:(double)value;
@end

__attribute__((swift_name("KotlinBoolean")))
@interface CommonBoolean : CommonNumber
- (instancetype)initWithBool:(BOOL)value;
+ (instancetype)numberWithBool:(BOOL)value;
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ArrayBridge")))
@interface CommonArrayBridge : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)arrayBridge __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonArrayBridge *shared __attribute__((swift_name("shared")));
- (id _Nullable)getArray:(CommonKotlinArray<id> *)array index:(int32_t)index __attribute__((swift_name("get(array:index:)")));
- (CommonConcreteIterator<id> *)iteratorArray:(CommonKotlinArray<id> *)array __attribute__((swift_name("iterator(array:)")));
- (void)setArray:(CommonKotlinArray<id> *)array index:(int32_t)index value:(id _Nullable)value __attribute__((swift_name("set(array:index:value:)")));
- (int32_t)sizeArray:(CommonKotlinArray<id> *)array __attribute__((swift_name("size(array:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ArrayListFactory")))
@interface CommonArrayListFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)arrayListFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonArrayListFactory *shared __attribute__((swift_name("shared")));
- (NSMutableArray<id> *)create __attribute__((swift_name("create()")));
- (NSMutableArray<id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (NSMutableArray<id> *)createElements:(id)elements __attribute__((swift_name("create(elements:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ByteArrayBridge")))
@interface CommonByteArrayBridge : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)byteArrayBridge __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonByteArrayBridge *shared __attribute__((swift_name("shared")));
- (CommonKotlinByteArray *)byteArrayFromNsData:(NSData *)nsData __attribute__((swift_name("byteArrayFrom(nsData:)")));
- (NSData *)nsDataFromByteArray:(CommonKotlinByteArray *)byteArray __attribute__((swift_name("nsDataFrom(byteArray:)")));
@end

__attribute__((swift_name("KotlinIterator")))
@protocol CommonKotlinIterator
@required
- (BOOL)hasNext __attribute__((swift_name("hasNext()")));
- (id _Nullable)next __attribute__((swift_name("next()")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ConcreteIterator")))
@interface CommonConcreteIterator<T> : CommonBase <CommonKotlinIterator>
- (instancetype)initWithDelegate:(id<CommonKotlinIterator>)delegate __attribute__((swift_name("init(delegate:)"))) __attribute__((objc_designated_initializer));
- (BOOL)hasNext __attribute__((swift_name("hasNext()")));
- (T _Nullable)next __attribute__((swift_name("next()")));
@end

__attribute__((swift_name("KotlinMapEntry")))
@protocol CommonKotlinMapEntry
@required
@property (readonly) id _Nullable key __attribute__((swift_name("key")));
@property (readonly) id _Nullable value __attribute__((swift_name("value")));
@end

__attribute__((swift_name("KotlinMutableDictionaryMutableEntry")))
@protocol CommonKotlinMutableMapMutableEntry <CommonKotlinMapEntry>
@required
- (id _Nullable)setValueNewValue:(id _Nullable)newValue __attribute__((swift_name("setValue(newValue:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ConcreteMutableEntry")))
@interface CommonConcreteMutableEntry<K, V> : CommonBase <CommonKotlinMutableMapMutableEntry>
- (instancetype)initWithDelegate:(id<CommonKotlinMutableMapMutableEntry>)delegate __attribute__((swift_name("init(delegate:)"))) __attribute__((objc_designated_initializer));
- (V _Nullable)setValueNewValue:(V _Nullable)newValue __attribute__((swift_name("setValue(newValue:)")));
@property (readonly) K _Nullable key __attribute__((swift_name("key")));
@property (readonly) V _Nullable value __attribute__((swift_name("value")));
@end

__attribute__((swift_name("KotlinMutableIterator")))
@protocol CommonKotlinMutableIterator <CommonKotlinIterator>
@required
- (void)remove __attribute__((swift_name("remove()")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ConcreteMutableIterator")))
@interface CommonConcreteMutableIterator<T> : CommonBase <CommonKotlinMutableIterator>
- (instancetype)initWithDelegate:(id<CommonKotlinMutableIterator>)delegate __attribute__((swift_name("init(delegate:)"))) __attribute__((objc_designated_initializer));
- (BOOL)hasNext __attribute__((swift_name("hasNext()")));
- (T _Nullable)next __attribute__((swift_name("next()")));
- (void)remove __attribute__((swift_name("remove()")));
@end

__attribute__((swift_name("KotlinListIterator")))
@protocol CommonKotlinListIterator <CommonKotlinIterator>
@required
- (BOOL)hasPrevious __attribute__((swift_name("hasPrevious()")));
- (int32_t)nextIndex __attribute__((swift_name("nextIndex()")));
- (id _Nullable)previous __attribute__((swift_name("previous()")));
- (int32_t)previousIndex __attribute__((swift_name("previousIndex()")));
@end

__attribute__((swift_name("KotlinMutableListIterator")))
@protocol CommonKotlinMutableListIterator <CommonKotlinListIterator, CommonKotlinMutableIterator>
@required
- (void)addElement:(id _Nullable)element __attribute__((swift_name("add(element:)")));
- (void)setElement:(id _Nullable)element __attribute__((swift_name("set(element:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ConcreteMutableListIterator")))
@interface CommonConcreteMutableListIterator<T> : CommonBase <CommonKotlinMutableListIterator>
- (instancetype)initWithDelegate:(id<CommonKotlinMutableListIterator>)delegate __attribute__((swift_name("init(delegate:)"))) __attribute__((objc_designated_initializer));
- (void)addElement:(T _Nullable)element __attribute__((swift_name("add(element:)")));
- (BOOL)hasNext __attribute__((swift_name("hasNext()")));
- (BOOL)hasPrevious __attribute__((swift_name("hasPrevious()")));
- (T _Nullable)next __attribute__((swift_name("next()")));
- (int32_t)nextIndex __attribute__((swift_name("nextIndex()")));
- (T _Nullable)previous __attribute__((swift_name("previous()")));
- (int32_t)previousIndex __attribute__((swift_name("previousIndex()")));
- (void)remove __attribute__((swift_name("remove()")));
- (void)setElement:(T _Nullable)element __attribute__((swift_name("set(element:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("HashMapBridge")))
@interface CommonHashMapBridge : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)hashMapBridge __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonHashMapBridge *shared __attribute__((swift_name("shared")));
- (void)clearHashMap:(CommonMutableDictionary<id, id> *)hashMap __attribute__((swift_name("clear(hashMap:)")));
- (BOOL)containsKeyHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key __attribute__((swift_name("containsKey(hashMap:key:)")));
- (BOOL)containsValueHashMap:(CommonMutableDictionary<id, id> *)hashMap value:(id _Nullable)value __attribute__((swift_name("containsValue(hashMap:value:)")));
- (CommonMutableDictionary<id, id> *)create __attribute__((swift_name("create()")));
- (CommonMutableDictionary<id, id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (CommonMutableDictionary<id, id> *)createInitialCapacity:(int32_t)initialCapacity loadFactor:(float)loadFactor __attribute__((swift_name("create(initialCapacity:loadFactor:)")));
- (CommonMutableDictionary<id, id> *)createOriginal:(NSDictionary<id, id> *)original __attribute__((swift_name("create(original:)")));
- (CommonMutableSet<CommonConcreteMutableEntry<id, id> *> *)entriesHashMap:(CommonMutableDictionary<id, id> *)hashMap __attribute__((swift_name("entries(hashMap:)")));
- (BOOL)equalsHashMap:(CommonMutableDictionary<id, id> *)hashMap other:(id _Nullable)other __attribute__((swift_name("equals(hashMap:other:)")));
- (id _Nullable)getHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key __attribute__((swift_name("get(hashMap:key:)")));
- (id _Nullable)getOrDefaultHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key defaultValue:(id _Nullable)defaultValue __attribute__((swift_name("getOrDefault(hashMap:key:defaultValue:)")));
- (int32_t)hashCodeHashMap:(CommonMutableDictionary<id, id> *)hashMap __attribute__((swift_name("hashCode(hashMap:)")));
- (BOOL)isEmptyHashMap:(CommonMutableDictionary<id, id> *)hashMap __attribute__((swift_name("isEmpty(hashMap:)")));
- (CommonMutableSet<id> *)keysHashMap:(CommonMutableDictionary<id, id> *)hashMap __attribute__((swift_name("keys(hashMap:)")));
- (id _Nullable)putHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key value:(id _Nullable)value __attribute__((swift_name("put(hashMap:key:value:)")));
- (void)putAllHashMap:(CommonMutableDictionary<id, id> *)hashMap from:(NSDictionary<id, id> *)from __attribute__((swift_name("putAll(hashMap:from:)")));
- (id _Nullable)putIfAbsentHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key value:(id _Nullable)value __attribute__((swift_name("putIfAbsent(hashMap:key:value:)")));
- (id _Nullable)removeHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key __attribute__((swift_name("remove(hashMap:key:)")));
- (BOOL)removeHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key value:(id _Nullable)value __attribute__((swift_name("remove(hashMap:key:value:)")));
- (id _Nullable)replaceHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key value:(id _Nullable)value __attribute__((swift_name("replace(hashMap:key:value:)")));
- (BOOL)replaceHashMap:(CommonMutableDictionary<id, id> *)hashMap key:(id _Nullable)key oldValue:(id _Nullable)oldValue newValue:(id _Nullable)newValue __attribute__((swift_name("replace(hashMap:key:oldValue:newValue:)")));
- (int32_t)sizeHashMap:(CommonMutableDictionary<id, id> *)hashMap __attribute__((swift_name("size(hashMap:)")));
- (id)valuesHashMap:(CommonMutableDictionary<id, id> *)hashMap __attribute__((swift_name("values(hashMap:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("HashSetFactory")))
@interface CommonHashSetFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)hashSetFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonHashSetFactory *shared __attribute__((swift_name("shared")));
- (CommonMutableSet<id> *)create __attribute__((swift_name("create()")));
- (CommonMutableSet<id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (CommonMutableSet<id> *)createInitialCapacity:(int32_t)initialCapacity loadFactor:(float)loadFactor __attribute__((swift_name("create(initialCapacity:loadFactor:)")));
- (CommonMutableSet<id> *)createElements:(id)elements __attribute__((swift_name("create(elements:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("LinkedHashMapBridge")))
@interface CommonLinkedHashMapBridge : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)linkedHashMapBridge __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonLinkedHashMapBridge *shared __attribute__((swift_name("shared")));
- (void)clearLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap __attribute__((swift_name("clear(linkedHashMap:)")));
- (BOOL)containsKeyLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key __attribute__((swift_name("containsKey(linkedHashMap:key:)")));
- (BOOL)containsValueLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap value:(id _Nullable)value __attribute__((swift_name("containsValue(linkedHashMap:value:)")));
- (CommonMutableDictionary<id, id> *)create __attribute__((swift_name("create()")));
- (CommonMutableDictionary<id, id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (CommonMutableDictionary<id, id> *)createInitialCapacity:(int32_t)initialCapacity loadFactor:(float)loadFactor __attribute__((swift_name("create(initialCapacity:loadFactor:)")));
- (CommonMutableDictionary<id, id> *)createOriginal:(NSDictionary<id, id> *)original __attribute__((swift_name("create(original:)")));
- (CommonMutableSet<id<CommonKotlinMutableMapMutableEntry>> *)entriesLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap __attribute__((swift_name("entries(linkedHashMap:)")));
- (BOOL)equalsLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap other:(id _Nullable)other __attribute__((swift_name("equals(linkedHashMap:other:)")));
- (id _Nullable)getLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key __attribute__((swift_name("get(linkedHashMap:key:)")));
- (id _Nullable)getOrDefaultLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key defaultValue:(id _Nullable)defaultValue __attribute__((swift_name("getOrDefault(linkedHashMap:key:defaultValue:)")));
- (int32_t)hashCodeLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap __attribute__((swift_name("hashCode(linkedHashMap:)")));
- (BOOL)isEmptyLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap __attribute__((swift_name("isEmpty(linkedHashMap:)")));
- (CommonMutableSet<id> *)keysLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap __attribute__((swift_name("keys(linkedHashMap:)")));
- (id _Nullable)putLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key value:(id _Nullable)value __attribute__((swift_name("put(linkedHashMap:key:value:)")));
- (void)putAllLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap from:(NSDictionary<id, id> *)from __attribute__((swift_name("putAll(linkedHashMap:from:)")));
- (id _Nullable)putIfAbsentLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key value:(id _Nullable)value __attribute__((swift_name("putIfAbsent(linkedHashMap:key:value:)")));
- (id _Nullable)removeLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key __attribute__((swift_name("remove(linkedHashMap:key:)")));
- (BOOL)removeLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key value:(id _Nullable)value __attribute__((swift_name("remove(linkedHashMap:key:value:)")));
- (id _Nullable)replaceLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key value:(id _Nullable)value __attribute__((swift_name("replace(linkedHashMap:key:value:)")));
- (BOOL)replaceLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap key:(id _Nullable)key oldValue:(id _Nullable)oldValue newValue:(id _Nullable)newValue __attribute__((swift_name("replace(linkedHashMap:key:oldValue:newValue:)")));
- (int32_t)sizeLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap __attribute__((swift_name("size(linkedHashMap:)")));
- (id)valuesLinkedHashMap:(CommonMutableDictionary<id, id> *)linkedHashMap __attribute__((swift_name("values(linkedHashMap:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("LinkedHashSetFactory")))
@interface CommonLinkedHashSetFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)linkedHashSetFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonLinkedHashSetFactory *shared __attribute__((swift_name("shared")));
- (CommonMutableSet<id> *)create __attribute__((swift_name("create()")));
- (CommonMutableSet<id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (CommonMutableSet<id> *)createInitialCapacity:(int32_t)initialCapacity loadFactor:(float)loadFactor __attribute__((swift_name("create(initialCapacity:loadFactor:)")));
- (CommonMutableSet<id> *)createElements:(id)elements __attribute__((swift_name("create(elements:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("KotlinArray")))
@interface CommonKotlinArray<T> : CommonBase
+ (instancetype)arrayWithSize:(int32_t)size init:(T _Nullable (^)(CommonInt *))init __attribute__((swift_name("init(size:init:)")));
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
- (T _Nullable)getIndex:(int32_t)index __attribute__((swift_name("get(index:)")));
- (id<CommonKotlinIterator>)iterator __attribute__((swift_name("iterator()")));
- (void)setIndex:(int32_t)index value:(T _Nullable)value __attribute__((swift_name("set(index:value:)")));
@property (readonly) int32_t size __attribute__((swift_name("size")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("KotlinByteArray")))
@interface CommonKotlinByteArray : CommonBase
+ (instancetype)arrayWithSize:(int32_t)size __attribute__((swift_name("init(size:)")));
+ (instancetype)arrayWithSize:(int32_t)size init:(CommonByte *(^)(CommonInt *))init __attribute__((swift_name("init(size:init:)")));
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
- (int8_t)getIndex:(int32_t)index __attribute__((swift_name("get(index:)")));
- (CommonKotlinByteIterator *)iterator __attribute__((swift_name("iterator()")));
- (void)setIndex:(int32_t)index value:(int8_t)value __attribute__((swift_name("set(index:value:)")));
@property (readonly) int32_t size __attribute__((swift_name("size")));
@end

__attribute__((swift_name("KotlinByteIterator")))
@interface CommonKotlinByteIterator : CommonBase <CommonKotlinIterator>
- (instancetype)init __attribute__((swift_name("init()"))) __attribute__((objc_designated_initializer));
+ (instancetype)new __attribute__((availability(swift, unavailable, message="use object initializers instead")));
- (CommonByte *)next __attribute__((swift_name("next()")));
- (int8_t)nextByte __attribute__((swift_name("nextByte()")));
@end

#pragma pop_macro("_Nullable_result")
#pragma clang diagnostic pop
NS_ASSUME_NONNULL_END

#endif /* __has_include(<common/common.h>) */

#endif /* J2ObjC_kotlinTypes_h */

// kotlin interop <<
