// kotlin interop >>
//
//  Generated by :j2objc-kompat:j2objcKotlinTypes.  DO NOT EDIT!
//

#ifndef J2ObjC_kotlinTypes_h
#define J2ObjC_kotlinTypes_h

#if __has_include(<common/common.h>)
#import <common/common.h>
#else

#import <Foundation/NSArray.h>
#import <Foundation/NSDictionary.h>
#import <Foundation/NSError.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSSet.h>
#import <Foundation/NSString.h>
#import <Foundation/NSValue.h>

@class CommonArrayFactory, CommonKotlinArray<T>, CommonArrayListFactory, CommonHashMapFactory, CommonHashSetFactory, CommonLinkedHashMapFactory, CommonLinkedHashSetFactory, CommonKotlinByteIterator, CommonKotlinByteArray, NSData;

@protocol CommonKotlinIterator;

NS_ASSUME_NONNULL_BEGIN
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunknown-warning-option"
#pragma clang diagnostic ignored "-Wincompatible-property-type"
#pragma clang diagnostic ignored "-Wnullability"

#pragma push_macro("_Nullable_result")
#if !__has_feature(nullability_nullable_result)
#undef _Nullable_result
#define _Nullable_result _Nullable
#endif

__attribute__((swift_name("KotlinBase")))
@interface CommonBase : NSObject
- (instancetype)init __attribute__((unavailable));
+ (instancetype)new __attribute__((unavailable));
+ (void)initialize __attribute__((objc_requires_super));
@end

@interface CommonBase (CommonBaseCopying) <NSCopying>
@end

__attribute__((swift_name("KotlinMutableSet")))
@interface CommonMutableSet<ObjectType> : NSMutableSet<ObjectType>
@end

__attribute__((swift_name("KotlinMutableDictionary")))
@interface CommonMutableDictionary<KeyType, ObjectType> : NSMutableDictionary<KeyType, ObjectType>
@end

@interface NSError (NSErrorCommonKotlinException)
@property (readonly) id _Nullable kotlinException;
@end

__attribute__((swift_name("KotlinNumber")))
@interface CommonNumber : NSNumber
- (instancetype)initWithChar:(char)value __attribute__((unavailable));
- (instancetype)initWithUnsignedChar:(unsigned char)value __attribute__((unavailable));
- (instancetype)initWithShort:(short)value __attribute__((unavailable));
- (instancetype)initWithUnsignedShort:(unsigned short)value __attribute__((unavailable));
- (instancetype)initWithInt:(int)value __attribute__((unavailable));
- (instancetype)initWithUnsignedInt:(unsigned int)value __attribute__((unavailable));
- (instancetype)initWithLong:(long)value __attribute__((unavailable));
- (instancetype)initWithUnsignedLong:(unsigned long)value __attribute__((unavailable));
- (instancetype)initWithLongLong:(long long)value __attribute__((unavailable));
- (instancetype)initWithUnsignedLongLong:(unsigned long long)value __attribute__((unavailable));
- (instancetype)initWithFloat:(float)value __attribute__((unavailable));
- (instancetype)initWithDouble:(double)value __attribute__((unavailable));
- (instancetype)initWithBool:(BOOL)value __attribute__((unavailable));
- (instancetype)initWithInteger:(NSInteger)value __attribute__((unavailable));
- (instancetype)initWithUnsignedInteger:(NSUInteger)value __attribute__((unavailable));
+ (instancetype)numberWithChar:(char)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedChar:(unsigned char)value __attribute__((unavailable));
+ (instancetype)numberWithShort:(short)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedShort:(unsigned short)value __attribute__((unavailable));
+ (instancetype)numberWithInt:(int)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedInt:(unsigned int)value __attribute__((unavailable));
+ (instancetype)numberWithLong:(long)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedLong:(unsigned long)value __attribute__((unavailable));
+ (instancetype)numberWithLongLong:(long long)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedLongLong:(unsigned long long)value __attribute__((unavailable));
+ (instancetype)numberWithFloat:(float)value __attribute__((unavailable));
+ (instancetype)numberWithDouble:(double)value __attribute__((unavailable));
+ (instancetype)numberWithBool:(BOOL)value __attribute__((unavailable));
+ (instancetype)numberWithInteger:(NSInteger)value __attribute__((unavailable));
+ (instancetype)numberWithUnsignedInteger:(NSUInteger)value __attribute__((unavailable));
@end

__attribute__((swift_name("KotlinByte")))
@interface CommonByte : CommonNumber
- (instancetype)initWithChar:(char)value;
+ (instancetype)numberWithChar:(char)value;
@end

__attribute__((swift_name("KotlinUByte")))
@interface CommonUByte : CommonNumber
- (instancetype)initWithUnsignedChar:(unsigned char)value;
+ (instancetype)numberWithUnsignedChar:(unsigned char)value;
@end

__attribute__((swift_name("KotlinShort")))
@interface CommonShort : CommonNumber
- (instancetype)initWithShort:(short)value;
+ (instancetype)numberWithShort:(short)value;
@end

__attribute__((swift_name("KotlinUShort")))
@interface CommonUShort : CommonNumber
- (instancetype)initWithUnsignedShort:(unsigned short)value;
+ (instancetype)numberWithUnsignedShort:(unsigned short)value;
@end

__attribute__((swift_name("KotlinInt")))
@interface CommonInt : CommonNumber
- (instancetype)initWithInt:(int)value;
+ (instancetype)numberWithInt:(int)value;
@end

__attribute__((swift_name("KotlinUInt")))
@interface CommonUInt : CommonNumber
- (instancetype)initWithUnsignedInt:(unsigned int)value;
+ (instancetype)numberWithUnsignedInt:(unsigned int)value;
@end

__attribute__((swift_name("KotlinLong")))
@interface CommonLong : CommonNumber
- (instancetype)initWithLongLong:(long long)value;
+ (instancetype)numberWithLongLong:(long long)value;
@end

__attribute__((swift_name("KotlinULong")))
@interface CommonULong : CommonNumber
- (instancetype)initWithUnsignedLongLong:(unsigned long long)value;
+ (instancetype)numberWithUnsignedLongLong:(unsigned long long)value;
@end

__attribute__((swift_name("KotlinFloat")))
@interface CommonFloat : CommonNumber
- (instancetype)initWithFloat:(float)value;
+ (instancetype)numberWithFloat:(float)value;
@end

__attribute__((swift_name("KotlinDouble")))
@interface CommonDouble : CommonNumber
- (instancetype)initWithDouble:(double)value;
+ (instancetype)numberWithDouble:(double)value;
@end

__attribute__((swift_name("KotlinBoolean")))
@interface CommonBoolean : CommonNumber
- (instancetype)initWithBool:(BOOL)value;
+ (instancetype)numberWithBool:(BOOL)value;
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ArrayFactory")))
@interface CommonArrayFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)arrayFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonArrayFactory *shared __attribute__((swift_name("shared")));
- (CommonKotlinArray<id> *)createSize:(int32_t)size init:(id _Nullable (^)(CommonInt *))init __attribute__((swift_name("create(size:init:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("ArrayListFactory")))
@interface CommonArrayListFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)arrayListFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonArrayListFactory *shared __attribute__((swift_name("shared")));
- (NSMutableArray<id> *)create __attribute__((swift_name("create()")));
- (NSMutableArray<id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (NSMutableArray<id> *)createElements:(id)elements __attribute__((swift_name("create(elements:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("HashMapFactory")))
@interface CommonHashMapFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)hashMapFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonHashMapFactory *shared __attribute__((swift_name("shared")));
- (CommonMutableDictionary<id, id> *)create __attribute__((swift_name("create()")));
- (CommonMutableDictionary<id, id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (CommonMutableDictionary<id, id> *)createInitialCapacity:(int32_t)initialCapacity loadFactor:(float)loadFactor __attribute__((swift_name("create(initialCapacity:loadFactor:)")));
- (CommonMutableDictionary<id, id> *)createOriginal:(NSDictionary<id, id> *)original __attribute__((swift_name("create(original:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("HashSetFactory")))
@interface CommonHashSetFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)hashSetFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonHashSetFactory *shared __attribute__((swift_name("shared")));
- (CommonMutableSet<id> *)create __attribute__((swift_name("create()")));
- (CommonMutableSet<id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (CommonMutableSet<id> *)createInitialCapacity:(int32_t)initialCapacity loadFactor:(float)loadFactor __attribute__((swift_name("create(initialCapacity:loadFactor:)")));
- (CommonMutableSet<id> *)createElements:(id)elements __attribute__((swift_name("create(elements:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("LinkedHashMapFactory")))
@interface CommonLinkedHashMapFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)linkedHashMapFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonLinkedHashMapFactory *shared __attribute__((swift_name("shared")));
- (CommonMutableDictionary<id, id> *)create __attribute__((swift_name("create()")));
- (CommonMutableDictionary<id, id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (CommonMutableDictionary<id, id> *)createInitialCapacity:(int32_t)initialCapacity loadFactor:(float)loadFactor __attribute__((swift_name("create(initialCapacity:loadFactor:)")));
- (CommonMutableDictionary<id, id> *)createOriginal:(NSDictionary<id, id> *)original __attribute__((swift_name("create(original:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("LinkedHashSetFactory")))
@interface CommonLinkedHashSetFactory : CommonBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)linkedHashSetFactory __attribute__((swift_name("init()")));
@property (class, readonly, getter=shared) CommonLinkedHashSetFactory *shared __attribute__((swift_name("shared")));
- (CommonMutableSet<id> *)create __attribute__((swift_name("create()")));
- (CommonMutableSet<id> *)createInitialCapacity:(int32_t)initialCapacity __attribute__((swift_name("create(initialCapacity:)")));
- (CommonMutableSet<id> *)createInitialCapacity:(int32_t)initialCapacity loadFactor:(float)loadFactor __attribute__((swift_name("create(initialCapacity:loadFactor:)")));
- (CommonMutableSet<id> *)createElements:(id)elements __attribute__((swift_name("create(elements:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("KotlinByteArray")))
@interface CommonKotlinByteArray : CommonBase
+ (instancetype)arrayWithSize:(int32_t)size __attribute__((swift_name("init(size:)")));
+ (instancetype)arrayWithSize:(int32_t)size init:(CommonByte *(^)(CommonInt *))init __attribute__((swift_name("init(size:init:)")));
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
- (int8_t)getIndex:(int32_t)index __attribute__((swift_name("get(index:)")));
- (CommonKotlinByteIterator *)iterator __attribute__((swift_name("iterator()")));
- (void)setIndex:(int32_t)index value:(int8_t)value __attribute__((swift_name("set(index:value:)")));
@property (readonly) int32_t size __attribute__((swift_name("size")));
@end

@interface CommonKotlinByteArray (Extensions)
- (NSData *)toNSData __attribute__((swift_name("toNSData()")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("BridgesKt")))
@interface CommonBridgesKt : CommonBase
+ (CommonKotlinByteArray *)toByteArray:(NSData *)receiver __attribute__((swift_name("toByteArray(_:)")));
@end

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("KotlinArray")))
@interface CommonKotlinArray<T> : CommonBase
+ (instancetype)arrayWithSize:(int32_t)size init:(T _Nullable (^)(CommonInt *))init __attribute__((swift_name("init(size:init:)")));
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
- (T _Nullable)getIndex:(int32_t)index __attribute__((swift_name("get(index:)")));
- (id<CommonKotlinIterator>)iterator __attribute__((swift_name("iterator()")));
- (void)setIndex:(int32_t)index value:(T _Nullable)value __attribute__((swift_name("set(index:value:)")));
@property (readonly) int32_t size __attribute__((swift_name("size")));
@end

__attribute__((swift_name("KotlinIterator")))
@protocol CommonKotlinIterator
@required
- (BOOL)hasNext __attribute__((swift_name("hasNext()")));
- (id _Nullable)next __attribute__((swift_name("next()")));
@end

__attribute__((swift_name("KotlinByteIterator")))
@interface CommonKotlinByteIterator : CommonBase <CommonKotlinIterator>
- (instancetype)init __attribute__((swift_name("init()"))) __attribute__((objc_designated_initializer));
+ (instancetype)new __attribute__((availability(swift, unavailable, message="use object initializers instead")));
- (CommonByte *)next __attribute__((swift_name("next()")));
- (int8_t)nextByte __attribute__((swift_name("nextByte()")));
@end

#pragma pop_macro("_Nullable_result")
#pragma clang diagnostic pop
NS_ASSUME_NONNULL_END

#endif /* __has_include(<common/common.h>) */

#endif /* J2ObjC_kotlinTypes_h */

// kotlin interop <<
