plugins {
    id("java")
    id("org.jetbrains.kotlin.multiplatform") version "$kotlin_version"
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenLocal()
    mavenCentral()
}

kotlin {
    targets {
        fromPreset(presets.jvm, "jvm")

        macosArm64("native") {
            binaries {
                framework {
                    embedBitcode("bitcode")
                    baseName = "Common"
                    isStatic = true
                }
            }
        }
    }

    sourceSets {
        configureEach {
            languageSettings {
                optIn("kotlin.Experimental")
                optIn("kotlin.time.ExperimentalTime")
            }
            kotlin {
                srcDir("src")
                exclude("**/*.java")
            }
        }

        commonMain {
            dependencies {
                implementation("org.jetbrains.kotlin:kotlin-stdlib-common:$kotlin_version")
            }
        }

        nativeMain {
        }
    }
}

tasks.register("copyFrameworkNative") {
    def buildType = project.findProperty("kotlin.build.type") ?: "DEBUG"

    dependsOn("link${buildType.toLowerCase().capitalize()}FrameworkNative")

    doLast {
        def frameworkFilename = "Common.framework"
        def srcFile = kotlin.targets.native.binaries.getFramework(buildType).outputFile
        def targetDir = file("build/bin/native").toString()

        copy {
            from(srcFile.parent)
            into(targetDir)
            include("${frameworkFilename}/**")
            include("${frameworkFilename}.dSYM")
        }
    }
}
