plugins {
    id("java")
    id("org.jetbrains.kotlin.multiplatform") version "$kotlinVersion"
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenLocal()
    mavenCentral()
}

kotlin {
    jvm()

    macosArm64("native") {
        binaries {
            framework {
                baseName = "Common"
                isStatic = true
            }
        }
    }

    sourceSets {
        configureEach {
            languageSettings {
                optIn("kotlin.Experimental")
                optIn("kotlin.time.ExperimentalTime")
            }

            kotlin {
                srcDir("src")
                exclude("**/*.java")
            }
        }

        commonMain {
            dependencies {
                implementation("org.jetbrains.kotlin:kotlin-stdlib-common:$kotlinVersion")
            }
        }
    }
}

tasks.register("copyFrameworkNative") {
    description("Copy Common.framework to `build/bin/native`")

    def buildType = project.findProperty("kotlin.build.type") as String ?: "DEBUG"

    dependsOn("jvmJar")
    dependsOn("link${buildType.toLowerCase().capitalize()}FrameworkNative")

    doLast {
        def frameworkFilename = "Common.framework"
        def srcFile = kotlin.targets.native.binaries.getFramework(buildType).outputFile
        def targetDir = file("build/bin/native").toString()

        copy {
            from(srcFile.parent)
            into(targetDir)
            include("${frameworkFilename}/**")
            include("${frameworkFilename}.dSYM")
        }
    }
}
