plugins {
    id("java")
    id("org.jetbrains.kotlin.multiplatform") version "$kotlin_version"
}

def iosArchLibrarySuffix = System.getenv("SDK_NAME")?.startsWith("iphoneos") ? "iosarm64" : "iosx64"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenLocal()
    mavenCentral()
}

kotlin {
    targets {
        fromPreset(presets.jvm, "jvm")

        final def iOSTarget = iosArchLibrarySuffix == "iosarm64" ? presets.iosArm64 : presets.iosX64
        fromPreset(iOSTarget, "ios") {
            binaries {
                framework {
                    embedBitcode("bitcode")
                    baseName = "Common"
                }
            }
        }

        macosX64("native") {
            binaries {
                framework {
                    embedBitcode("bitcode")
                    baseName = "Common"
                    isStatic = true
                }
            }
        }
    }

    sourceSets {
        configureEach {
            languageSettings {
                optIn("kotlin.Experimental")
                optIn("kotlin.time.ExperimentalTime")
            }
            kotlin {
                srcDir("src")
                exclude("**/*.java")
            }
        }

        commonMain {
            dependencies {
                implementation("org.jetbrains.kotlin:kotlin-stdlib-common:$kotlin_version")
            }
        }

        iosMain {
        }

        nativeMain {
        }
    }
}

tasks.register("copyFramework") {
    def buildType = project.findProperty("kotlin.build.type") ?: "DEBUG"

    dependsOn("link${buildType.toLowerCase().capitalize()}FrameworkIos")

    doLast {
        def frameworkFilename = "Common.framework"
        def srcFile = kotlin.targets.ios.binaries.getFramework(buildType).outputFile
        def targetDir = file("build/bin/ios").toString()
        def j2objcTarget = file("../core/generated-objc").toString()

        copy {
            from(srcFile.parent)
            into(targetDir)
            include("${frameworkFilename}/**")
            include("${frameworkFilename}.dSYM")
        }

        copy {
            from("${srcFile}/headers")
            into(j2objcTarget)
            include("**/*.h")
        }
    }
}

tasks.register("copyFrameworkNative") {
    def buildType = project.findProperty("kotlin.build.type") ?: "DEBUG"

    dependsOn("link${buildType.toLowerCase().capitalize()}FrameworkNative")

    doLast {
        def frameworkFilename = "Common.framework"
        def srcFile = kotlin.targets.native.binaries.getFramework(buildType).outputFile
        def targetDir = file("build/bin/native").toString()

        copy {
            from(srcFile.parent)
            into(targetDir)
            include("${frameworkFilename}/**")
            include("${frameworkFilename}.dSYM")
        }
    }
}
