detekt_version=1.23.1
group=com.mirego
kotlin.build.type=DEBUG
kotlin.code.style=official
kotlin.compiler.preciseCompilationResultsBackup=true
kotlin.compiler.suppressExperimentalICOptimizationsWarning=true
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.import.enableKgpDependencyResolution=true
kotlin.native.ignoreDisabledTargets=true
kotlin_version=1.9.10
org.gradle.caching=false
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xms1g -Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
version=3.0
