@file:Suppress("LocalVariableName", "VariableNaming", "PropertyName")

import org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin
import org.jetbrains.kotlin.gradle.targets.js.npm.LockFileMismatchReport
import org.jetbrains.kotlin.gradle.targets.js.npm.NpmExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinNativeCompile
import java.net.URI

val detekt_version: String by extra
val kotlin_version: String by extra

val isCi = System.getenv().containsKey("CI")

repositories {
    mavenCentral()
    google()
    maven(url = URI("https://oss.sonatype.org/content/repositories/snapshots"))
}

plugins {
    idea
    kotlin("multiplatform")
    id("com.google.devtools.ksp")
    id("dev.detekt")
    id("dev.mokkery")
    `maven-publish`
}

kotlin {
    jvmToolchain(11)

    jvm()

    js(IR) {
        outputModuleName.set("j2objc-kompat")
        browser()
        binaries.executable()

        rootProject.plugins.withType<NodeJsRootPlugin> {
            rootProject.the<NpmExtension>().packageLockMismatchReport.set(LockFileMismatchReport.WARNING)
            rootProject.the<NpmExtension>().packageLockAutoReplace.set(true)
        }
    }

    macosArm64 {
        binaries {
            framework {
                baseName = "common"
                binaryOption("bundleId", "com.google.j2objc.kompat")
                isStatic = true
            }
        }
    }

    iosArm64()
    iosSimulatorArm64()

    tvosArm64()
    tvosSimulatorArm64()

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain {
        }

        commonTest {
            dependencies {
                implementation(kotlin("test"))
                implementation("org.slf4j:slf4j-nop:2.0.17")
            }
        }

        jsMain {
            dependencies {
                api(kotlin("stdlib-js"))
            }
        }

        all {
            languageSettings.optIn("kotlin.experimental.ExperimentalObjCName")
            languageSettings.optIn("kotlin.experimental.ExperimentalObjCRefinement")
            languageSettings.optIn("kotlin.js.ExperimentalJsExport")
            languageSettings.optIn("kotlin.time.ExperimentalTime")
        }
    }

    compilerOptions {
        allWarningsAsErrors.set(isCi)
        extraWarnings.set(true)
        freeCompilerArgs.add("-Xallow-condition-implies-returns-contracts")
        freeCompilerArgs.add("-Xallow-contracts-on-more-functions")
        freeCompilerArgs.add("-Xallow-holdsin-contract")
        freeCompilerArgs.add("-Xallow-reified-type-in-catch")
        freeCompilerArgs.add("-Xannotation-default-target=param-property")
        freeCompilerArgs.add("-Xannotation-target-all")
        freeCompilerArgs.add("-Xconsistent-data-class-copy-visibility")
        freeCompilerArgs.add("-Xcontext-parameters")
        freeCompilerArgs.add("-Xcontext-sensitive-resolution")
        freeCompilerArgs.add("-Xdata-flow-based-exhaustiveness")
        freeCompilerArgs.add("-Xexpect-actual-classes")
        freeCompilerArgs.add("-Xmulti-dollar-interpolation")
        freeCompilerArgs.add("-Xnested-type-aliases")
        freeCompilerArgs.add("-Xnon-local-break-continue")
        freeCompilerArgs.add("-Xreturn-value-checker=full")
        freeCompilerArgs.add("-Xwhen-guards")
    }
}

dependencies {
    detektPlugins("dev.detekt:detekt-rules-ktlint-wrapper:$detekt_version")
}

// Disable interfaces and swift name mangling
tasks.withType<KotlinNativeCompile>().configureEach {
    compilerOptions {
        freeCompilerArgs.add("-Xbinary=objcExportDisableSwiftMemberNameMangling=true")
        freeCompilerArgs.add("-Xbinary=objcExportIgnoreInterfaceMethodCollisions=true")
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    maxParallelForks = Runtime.getRuntime().availableProcessors()
}

tasks.register("j2objcKotlinTypes") {
    group = "Interop"
    description = "Generate `J2ObjC_kotlinTypes.h` and copy it to `jre_emul/Classes`"

    if (!isCi) {
        doFirst {
            copy {
                from(layout.buildDirectory.file("bin/macosArm64/debugFramework/common.framework/Headers").get().asFile)
                into(layout.buildDirectory.file("interop").get().asFile)

                include("common.h")
                rename { "J2ObjC_kotlinTypes.h" }

                eachFile {
                    file.writeText(
                        """// kotlin interop >>
//
//  Generated by :j2objc-kompat:j2objcKotlinTypes.  DO NOT EDIT!
//

#ifndef J2ObjC_kotlinTypes_h
#define J2ObjC_kotlinTypes_h

#if __has_include(<common/common.h>)
#import <common/common.h>
#else

${file.readText().trim('\n')}

#endif /* __has_include(<common/common.h>) */

#endif /* J2ObjC_kotlinTypes_h */

// kotlin interop <<
""",
                    )
                }
            }

            providers.exec {
                commandLine(
                    "rsync", "-acI", "--no-times",
                    layout.buildDirectory.file("interop/J2ObjC_kotlinTypes.h").get().asFile.absolutePath,
                    layout.projectDirectory.file("../jre_emul/Classes").asFile.absolutePath,
                )
            }
        }

        inputs.dir(file("src"))

        outputs.cacheIf { true }
        outputs.file(file("../jre_emul/Classes/J2ObjC_kotlinTypes.h"))

        dependsOn("linkDebugFrameworkMacosArm64")
    }
}

detekt {
    autoCorrect = !isCi
    ignoreFailures = !isCi
    buildUponDefaultConfig = true
    config.setFrom("../../../detekt-config.yml")
    source.setFrom(file("src").listFiles()!!.filter { it.name.endsWith("Main") || it.name.endsWith("Test") })
}

idea {
    module {
        excludeDirs.add(file("gradle/wrapper"))
        excludeDirs.add(file("kotlin-js-store"))
    }
}
