import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.targets.js.npm.tasks.KotlinNpmInstallTask
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnLockMismatchReport
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension

val kotlinVersion: String by extra

val isCi = System.getenv("JENKINS_HOME")?.isNotBlank() == true
    || System.getenv("GITHUB_ACTIONS")?.isNotBlank() == true

repositories {
    mavenLocal()
    mavenCentral()
    google()
}

plugins {
    idea
    kotlin("multiplatform")
    `maven-publish`
}

@OptIn(ExperimentalKotlinGradlePluginApi::class)
kotlin {
    targetHierarchy.default()

    jvmToolchain(11)

    jvm {
        compilations.all {
            kotlinOptions.allWarningsAsErrors = true
        }
    }

    js(IR) {
        moduleName = "j2objc-kompat"
        browser()
        binaries.executable()

        rootProject.plugins.withType(YarnPlugin::class.java).configureEach {
            rootProject.the<YarnRootExtension>().yarnLockMismatchReport = YarnLockMismatchReport.WARNING
            rootProject.the<YarnRootExtension>().reportNewYarnLock = false
            rootProject.the<YarnRootExtension>().yarnLockAutoReplace = false
        }

        rootProject.tasks.withType(KotlinNpmInstallTask::class.java).named("kotlinNpmInstall").configure {
            args.addAll(listOf("--network-concurrency", "1", "--mutex", "network"))
        }
    }

    macosArm64 {
        binaries {
            framework {
                baseName = "common"
                binaryOption("bundleId", "com.google.j2objc.kompat")
                isStatic = true
            }
        }
    }

    ios()
    iosSimulatorArm64()

    tvos()
    tvosSimulatorArm64()

    sourceSets {
        named("commonTest") {
            dependencies {
                implementation(kotlin("test", kotlinVersion))
            }
        }

        val iosMain by sourceSets.getting
        val iosTest by sourceSets.getting
        val iosSimulatorArm64Main by sourceSets.getting
        val iosSimulatorArm64Test by sourceSets.getting
        iosSimulatorArm64Main.dependsOn(iosMain)
        iosSimulatorArm64Test.dependsOn(iosTest)

        val tvosMain by sourceSets.getting
        val tvosTest by sourceSets.getting
        val tvosSimulatorArm64Main by sourceSets.getting
        val tvosSimulatorArm64Test by sourceSets.getting
        tvosSimulatorArm64Main.dependsOn(tvosMain)
        tvosSimulatorArm64Test.dependsOn(tvosTest)

        all {
            languageSettings.optIn("kotlin.experimental.ExperimentalObjCName")
            languageSettings.optIn("kotlin.js.ExperimentalJsExport")
            languageSettings.optIn("kotlin.time.ExperimentalTime")
        }
    }
}

idea {
    module {
        excludeDirs.add(file("gradle/wrapper"))
    }
}

tasks.register("j2objcKotlinTypes") {
    group = "Interop"
    description = "Generate `J2ObjC_kotlinTypes.h` and copy it to `jre_emul/Classes`"

    if (!isCi) {
        doFirst {
            copy {
                from("build/bin/macosArm64/debugFramework/common.framework/Headers")
                into("build/interop")

                include("common.h")
                rename { "J2ObjC_kotlinTypes.h" }

                eachFile {
                    file.writeText(
                        """// kotlin interop >>
//
//  Generated by :j2objc-kompat:j2objcKotlinTypes.  DO NOT EDIT!
//

#ifndef J2ObjC_kotlinTypes_h
#define J2ObjC_kotlinTypes_h

#if __has_include(<common/common.h>)
#import <common/common.h>
#else

${file.readText().trim('\n')}

#endif /* __has_include(<common/common.h>) */

#endif /* J2ObjC_kotlinTypes_h */

// kotlin interop <<
"""
                    )
                }
            }

            exec {
                commandLine(
                    "rsync", "-acI", "--no-times",
                    file("build/interop/J2ObjC_kotlinTypes.h").absolutePath,
                    file("../jre_emul/Classes").absolutePath
                )
            }
        }

        inputs.dir(file("src"))

        outputs.cacheIf { true }
        outputs.file(file("../jre_emul/Classes/J2ObjC_kotlinTypes.h"))

        dependsOn("linkDebugFrameworkMacosArm64")
    }
}
