import io.gitlab.arturbosch.detekt.Detekt
import io.gitlab.arturbosch.detekt.DetektCreateBaselineTask
import org.gradle.internal.os.OperatingSystem
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.TestExecutable
import org.jetbrains.kotlin.gradle.targets.js.npm.tasks.KotlinNpmInstallTask
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnLockMismatchReport
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension
import java.io.ByteArrayOutputStream

val kotlin_version: String by extra
val detekt_version: String by extra

val isCi = System.getenv().containsKey("CI")

repositories {
    mavenLocal()
    mavenCentral()
    google()
}

plugins {
    idea
    kotlin("multiplatform")
    id("io.gitlab.arturbosch.detekt")
    // id("io.github.detekt.gradle.compiler-plugin")
    `maven-publish`
}

@OptIn(ExperimentalKotlinGradlePluginApi::class)
kotlin {
    targetHierarchy.default()

    jvmToolchain(11)

    jvm {
        compilations.all {
            kotlinOptions.allWarningsAsErrors = true
        }
    }

    js(IR) {
        moduleName = "j2objc-kompat"
        browser()
        binaries.executable()

        rootProject.plugins.withType(YarnPlugin::class.java).configureEach {
            rootProject.the<YarnRootExtension>().yarnLockMismatchReport = YarnLockMismatchReport.WARNING
            rootProject.the<YarnRootExtension>().yarnLockAutoReplace = true
        }

        rootProject.tasks.withType(KotlinNpmInstallTask::class.java).named("kotlinNpmInstall").configure {
            args.addAll(listOf("--network-concurrency", "1", "--mutex", "network"))
        }
    }

    macosArm64 {
        binaries {
            framework {
                baseName = "common"
                binaryOption("bundleId", "com.google.j2objc.kompat")
                isStatic = true
            }
        }
    }

    ios { compilations.configureEach { compilerOptions.configure { freeCompilerArgs.add("-Xallocator=custom") } } }
    iosSimulatorArm64 { compilations.configureEach { compilerOptions.configure { freeCompilerArgs.add("-Xallocator=custom") } } }

    val iosMain by sourceSets.getting
    val iosTest by sourceSets.getting
    val iosSimulatorArm64Main by sourceSets.getting
    val iosSimulatorArm64Test by sourceSets.getting
    iosSimulatorArm64Main.dependsOn(iosMain)
    iosSimulatorArm64Test.dependsOn(iosTest)

    tvos { compilations.configureEach { compilerOptions.configure { freeCompilerArgs.add("-Xallocator=custom") } } }
    tvosSimulatorArm64 { compilations.configureEach { compilerOptions.configure { freeCompilerArgs.add("-Xallocator=custom") } } }

    val tvosMain by sourceSets.getting
    val tvosTest by sourceSets.getting
    val tvosSimulatorArm64Main by sourceSets.getting
    val tvosSimulatorArm64Test by sourceSets.getting
    tvosSimulatorArm64Main.dependsOn(tvosMain)
    tvosSimulatorArm64Test.dependsOn(tvosTest)

    // Xcode 15 new linker is incompatible with Kotlin, tell it to use the old linker
    val isXcode15 = if (!OperatingSystem.current().isMacOsX) false else {
        val xcodeBuildOutput = ByteArrayOutputStream()
        exec { commandLine("xcrun", "xcodebuild", "-version"); standardOutput = xcodeBuildOutput; isIgnoreExitValue = true }
        xcodeBuildOutput.toString().contains("Xcode 15.")
    }
    if (isXcode15) {
        targets.withType<KotlinNativeTarget> { binaries.withType<TestExecutable> { linkerOpts += "-ld64" } }
    }

    sourceSets {
        named("commonTest") {
            dependencies {
                api(kotlin("test", kotlin_version))
            }
        }

        all {
            languageSettings.optIn("kotlin.experimental.ExperimentalObjCName")
            languageSettings.optIn("kotlin.js.ExperimentalJsExport")
            languageSettings.optIn("kotlin.time.ExperimentalTime")
        }
    }
}

dependencies {
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:$detekt_version")
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    maxParallelForks = (Runtime.getRuntime().availableProcessors() / 2).takeIf { it > 0 } ?: 1
}

tasks.register("j2objcKotlinTypes") {
    group = "Interop"
    description = "Generate `J2ObjC_kotlinTypes.h` and copy it to `jre_emul/Classes`"

    if (!isCi) {
        doFirst {
            copy {
                from("${layout.buildDirectory.asFile.get()}/bin/macosArm64/debugFramework/common.framework/Headers")
                into("${layout.buildDirectory.asFile.get()}/interop")

                include("common.h")
                rename { "J2ObjC_kotlinTypes.h" }

                eachFile {
                    file.writeText(
                        """// kotlin interop >>
//
//  Generated by :j2objc-kompat:j2objcKotlinTypes.  DO NOT EDIT!
//

#ifndef J2ObjC_kotlinTypes_h
#define J2ObjC_kotlinTypes_h

#if __has_include(<common/common.h>)
#import <common/common.h>
#else

${file.readText().trim('\n')}

#endif /* __has_include(<common/common.h>) */

#endif /* J2ObjC_kotlinTypes_h */

// kotlin interop <<
"""
                    )
                }
            }

            exec {
                commandLine(
                    "rsync", "-acI", "--no-times",
                    file("${layout.buildDirectory.asFile.get()}/interop/J2ObjC_kotlinTypes.h").absolutePath,
                    file("../jre_emul/Classes").absolutePath
                )
            }
        }

        inputs.dir(file("src"))

        outputs.cacheIf { true }
        outputs.file(file("../jre_emul/Classes/J2ObjC_kotlinTypes.h"))

        dependsOn("linkDebugFrameworkMacosArm64")
    }
}

detekt {
    autoCorrect = true
    buildUponDefaultConfig = true
    config.setFrom("../../../detekt-config.yml")
    source.setFrom(file("src").listFiles()!!.filter { it.name.endsWith("Main") || it.name.endsWith("Test") })
}

tasks.withType<Detekt>().configureEach { jvmTarget = JavaVersion.VERSION_11.toString() }
tasks.withType<DetektCreateBaselineTask>().configureEach { jvmTarget = JavaVersion.VERSION_11.toString() }

idea {
    module {
        excludeDirs.add(file("gradle/wrapper"))
    }
}
