detekt_version=2.0.0-alpha.2
group=com.google.j2objc
kotlin.apple.xcodeCompatibility.nowarn=true
kotlin.code.style=official
kotlin.compiler.suppressExperimentalICOptimizationsWarning=true
kotlin.incremental.native=true
kotlin.js.ir.output.granularity=whole-program
kotlin.js.yarn=false
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.native.binary.latin1Strings=true
kotlin.native.binary.objcExportBlockExplicitParameterNames=true
kotlin.native.binary.pagedAllocator=false
kotlin.native.ignoreDisabledTargets=true
kotlin.suppressGradlePluginWarnings=TestApiDependencyWarning
kotlin_version=2.3.10
ksp_version=2.3.5
mokkery_version=3.2.0
org.gradle.caching=true
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xmx8g -Dkotlin.daemon.jvm.options\="-Xmx8g" -Dfile.encoding=UTF-8 --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
org.gradle.parallel=true
version=3.0
