checkerFrameworkVersion=3.32.0
group=com.google.j2objc
kotlin.code.style=official
kotlin.compiler.preciseCompilationResultsBackup=true
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.import.enableKgpDependencyResolution=true
kotlin.native.ignoreDisabledTargets=true
kotlinVersion=1.8.22
org.gradle.caching=false
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xms512m -Xmx3g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
version=3.0
